### PR TITLE
Update dependencies to latest

### PR DESCRIPTION
**Pull request by S-YOU**

### CODE REVIEW

**Comment by kazegusuri** [comment]
Thank you for the PR. Please rebase from master.

**Comment by shuya-takano** [comment]
@kazegusuri 

> Thank you for the PR. Please rebase from master.

sorry for late response, I have rebased this pull request.

**Comment by S-YOU** [comment]
@kazegusuri I'have rebased it, thanks

**Review by kazegusuri — APPROVED** [review]

**Comment by kazegusuri** [comment]
thank you!

**Pull request merged**
